name: Trigger auto deployment for container-app-oohu6dkcztk64

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-oohu6dkcztk64-AutoDeployTrigger-4f092960-9d07-4051-8807-48e43475b07b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOOHU6DKCZTK64_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOOHU6DKCZTK64_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOOHU6DKCZTK64_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOOHU6DKCZTK64_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOOHU6DKCZTK64_REGISTRY_PASSWORD }}
          containerAppName: container-app-oohu6dkcztk64
          resourceGroup: djangoappspaces985e9b7b
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


